version: '3.0'

services: 
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postrgesql/data
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

volumes: 
  pgdata:
